version: '3'
services:

    jupyter_notebook_server:
        build: .
        volumes:
            - ./LearningMaterials:/LearningMaterials            
        network_mode: host
        command: bash -c "jupyter notebook --allow-root --port 8888 --ip=0.0.0.0 --NotebookApp.password=sha1:56fa123e9f85:09c8b21ac5e02ae483033416e292a233fd126955"
    