version: '3'
services:

    jupyter_notebook_server:
        build: .
        volumes:
            - ./LearningMaterials:/LearningMaterials            
        network_mode: host
        command: bash -c "jupyter notebook --allow-root --port 8888 --ip=0.0.0.0 --NotebookApp.password=sha1:883823d89aed:a6abbf15373e44d5226fb47034d370f31f9cdb16"
    